Russian translations
Dhaval2404/ImagePicker pull request #209
Opened 2021-05-30 03:36 UTC by Khudoyshukur

## 🚀 Description

## 📄 Motivation and Context

## 🧪 How Has This Been Tested?

## 📷 Screenshots (if appropriate)

## 📦 Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-05-30 03:37 UTC, Khudoyshukur commented
Russian translations

2021-08-13 19:12 UTC, Dhaval2404 commented on imagepicker/src/main/res/values-ru/strings.xml
> +    <string name="permission_camera_denied">![CDATA[Camera требуется разрешение для фотографирования. Разрешите, пожалуйста, Настройки > Разрешения.]]</string>
Can you please review this once?

2021-08-25 14:42 UTC, palushin86 commented on imagepicker/src/main/res/values-ru/strings.xml
> +    <string name="title_choose_image_provider">Выбирать</string>
it is worth writing here: 
<string name="title_choose_image_provider">Выбор</string>
or
<string name="title_choose_image_provider">Выбор источника</string>

2021-08-25 15:13 UTC, Khudoyshukur commented
Thanks for your comment. I am not a native Russian speaker. I just translated them with the help of online tools. If you are a native I would ask you for checking all the translations...
--
Sent from Mail.ru app for Android Wednesday, 25 August 2021, 07:43PM +05:00 from palushin86  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  imagepicker/src/main/res/values-ru/strings.xml :
> @@ -0,0 +1,28 @@
>+
>+
>+    Image Picker
>+    .imagepicker.provider
>+
>+    Выбирать
>
>it is worth writing here:
>Выбор
>or
>Выбор источника
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .

2021-08-28 10:15 UTC, palushin86 commented on imagepicker/src/main/res/values-ru/strings.xml
> +    <string name="permission_camera_denied">![CDATA[Camera требуется разрешение для фотографирования. Разрешите, пожалуйста, Настройки > Разрешения.]]</string>
<string name="permission_camera_denied">![CDATA[Для съемки требуется доступ к камере. Пожалуйста, дайте разрешение через Настройки > Разрешения.]]</string>

2021-08-28 10:20 UTC, palushin86 commented on imagepicker/src/main/res/values-ru/strings.xml
> +    <string name="error_failed_to_create_camera_image_file">Не удалось создать файл изображения камеры</string>
<string name="error_failed_to_create_camera_image_file">Не удалось создать снимок</string>

2021-08-28 10:21 UTC, palushin86 commented on imagepicker/src/main/res/values-ru/strings.xml
> +    <string name="error_failed_pick_gallery_image">Не удалось выбрать изображение галереи</string>
<string name="error_failed_pick_gallery_image">Не удалось выбрать изображение из галереи</string>

2021-08-28 10:24 UTC, palushin86 commented on imagepicker/src/main/res/values-ru/strings.xml
> +    <string name="ucrop_scale">Шкала</string>
<string name="ucrop_scale">Масштаб</string>

2021-08-28 10:32 UTC, palushin86 commented on imagepicker/src/main/res/values-ru/strings.xml
> +    <string name="ucrop_label_edit_photo">Редактировать фотографию</string>
Фоторедактор

2021-08-28 10:41 UTC, palushin86 requested changes
I checked all the translations at your request. I suggest doing this

2021-10-15 08:27 UTC, Orange1353 commented
what do you thing about accept this issue? it will be very helpful, thanks

2021-10-15 08:28 UTC, Orange1353 commented
/

2022-06-03 00:46 UTC, closed without merging